CREATE TABLE `tabItem` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `naming_series` varchar(140) DEFAULT NULL,
  `item_code` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `stock_uom` varchar(140) DEFAULT NULL,
  `disabled` tinyint(4) NOT NULL DEFAULT 0,
  `allow_alternative_item` tinyint(4) NOT NULL DEFAULT 0,
  `is_stock_item` tinyint(4) NOT NULL DEFAULT 1,
  `has_variants` tinyint(4) NOT NULL DEFAULT 0,
  `opening_stock` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `valuation_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `standard_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `is_fixed_asset` tinyint(4) NOT NULL DEFAULT 0,
  `auto_create_assets` tinyint(4) NOT NULL DEFAULT 0,
  `is_grouped_asset` tinyint(4) NOT NULL DEFAULT 0,
  `asset_category` varchar(140) DEFAULT NULL,
  `asset_naming_series` varchar(140) DEFAULT NULL,
  `over_delivery_receipt_allowance` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `over_billing_allowance` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `image` text DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `shelf_life_in_days` int(11) NOT NULL DEFAULT 0,
  `end_of_life` date DEFAULT '2099-12-31',
  `default_material_request_type` varchar(140) DEFAULT 'Purchase',
  `valuation_method` varchar(140) DEFAULT NULL,
  `warranty_period` varchar(140) DEFAULT NULL,
  `weight_per_unit` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `weight_uom` varchar(140) DEFAULT NULL,
  `allow_negative_stock` tinyint(4) NOT NULL DEFAULT 0,
  `has_batch_no` tinyint(4) NOT NULL DEFAULT 0,
  `create_new_batch` tinyint(4) NOT NULL DEFAULT 0,
  `batch_number_series` varchar(140) DEFAULT NULL,
  `has_expiry_date` tinyint(4) NOT NULL DEFAULT 0,
  `retain_sample` tinyint(4) NOT NULL DEFAULT 0,
  `sample_quantity` int(11) NOT NULL DEFAULT 0,
  `has_serial_no` tinyint(4) NOT NULL DEFAULT 0,
  `serial_no_series` varchar(140) DEFAULT NULL,
  `variant_of` varchar(140) DEFAULT NULL,
  `variant_based_on` varchar(140) DEFAULT 'Item Attribute',
  `enable_deferred_expense` tinyint(4) NOT NULL DEFAULT 0,
  `no_of_months_exp` int(11) NOT NULL DEFAULT 0,
  `enable_deferred_revenue` tinyint(4) NOT NULL DEFAULT 0,
  `no_of_months` int(11) NOT NULL DEFAULT 0,
  `purchase_uom` varchar(140) DEFAULT NULL,
  `min_order_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `safety_stock` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `is_purchase_item` tinyint(4) NOT NULL DEFAULT 1,
  `lead_time_days` int(11) NOT NULL DEFAULT 0,
  `last_purchase_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `is_customer_provided_item` tinyint(4) NOT NULL DEFAULT 0,
  `customer` varchar(140) DEFAULT NULL,
  `delivered_by_supplier` tinyint(4) NOT NULL DEFAULT 0,
  `country_of_origin` varchar(140) DEFAULT NULL,
  `customs_tariff_number` varchar(140) DEFAULT NULL,
  `sales_uom` varchar(140) DEFAULT NULL,
  `grant_commission` tinyint(4) NOT NULL DEFAULT 1,
  `is_sales_item` tinyint(4) NOT NULL DEFAULT 1,
  `max_discount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `inspection_required_before_purchase` tinyint(4) NOT NULL DEFAULT 0,
  `quality_inspection_template` varchar(140) DEFAULT NULL,
  `inspection_required_before_delivery` tinyint(4) NOT NULL DEFAULT 0,
  `include_item_in_manufacturing` tinyint(4) NOT NULL DEFAULT 1,
  `is_sub_contracted_item` tinyint(4) NOT NULL DEFAULT 0,
  `default_bom` varchar(140) DEFAULT NULL,
  `customer_code` text DEFAULT NULL,
  `default_item_manufacturer` varchar(140) DEFAULT NULL,
  `default_manufacturer_part_no` varchar(140) DEFAULT NULL,
  `total_projected_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  UNIQUE KEY `item_code` (`item_code`),
  KEY `item_name` (`item_name`),
  KEY `item_group` (`item_group`),
  KEY `disabled` (`disabled`),
  KEY `variant_of` (`variant_of`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabSupplier` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `naming_series` varchar(140) DEFAULT NULL,
  `supplier_name` varchar(140) DEFAULT NULL,
  `country` varchar(140) DEFAULT NULL,
  `supplier_group` varchar(140) DEFAULT NULL,
  `supplier_type` varchar(140) DEFAULT 'Company',
  `is_transporter` tinyint(4) NOT NULL DEFAULT 0,
  `image` text DEFAULT NULL,
  `default_currency` varchar(140) DEFAULT NULL,
  `default_bank_account` varchar(140) DEFAULT NULL,
  `default_price_list` varchar(140) DEFAULT NULL,
  `is_internal_supplier` tinyint(4) NOT NULL DEFAULT 0,
  `represents_company` varchar(140) DEFAULT NULL,
  `supplier_details` text DEFAULT NULL,
  `website` varchar(140) DEFAULT NULL,
  `language` varchar(140) DEFAULT NULL,
  `tax_id` varchar(140) DEFAULT NULL,
  `tax_category` varchar(140) DEFAULT NULL,
  `tax_withholding_category` varchar(140) DEFAULT NULL,
  `supplier_primary_address` varchar(140) DEFAULT NULL,
  `primary_address` text DEFAULT NULL,
  `supplier_primary_contact` varchar(140) DEFAULT NULL,
  `mobile_no` varchar(140) DEFAULT NULL,
  `email_id` varchar(140) DEFAULT NULL,
  `payment_terms` varchar(140) DEFAULT NULL,
  `allow_purchase_invoice_creation_without_purchase_order` tinyint(4) NOT NULL DEFAULT 0,
  `allow_purchase_invoice_creation_without_purchase_receipt` tinyint(4) NOT NULL DEFAULT 0,
  `is_frozen` tinyint(4) NOT NULL DEFAULT 0,
  `disabled` tinyint(4) NOT NULL DEFAULT 0,
  `warn_rfqs` tinyint(4) NOT NULL DEFAULT 0,
  `warn_pos` tinyint(4) NOT NULL DEFAULT 0,
  `prevent_rfqs` tinyint(4) NOT NULL DEFAULT 0,
  `prevent_pos` tinyint(4) NOT NULL DEFAULT 0,
  `on_hold` tinyint(4) NOT NULL DEFAULT 0,
  `hold_type` varchar(140) DEFAULT NULL,
  `release_date` date DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabMaterial Request` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `naming_series` varchar(140) DEFAULT NULL,
  `title` varchar(140) DEFAULT '{material_request_type}',
  `material_request_type` varchar(140) DEFAULT NULL,
  `customer` varchar(140) DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `transaction_date` date DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `scan_barcode` varchar(140) DEFAULT NULL,
  `set_from_warehouse` varchar(140) DEFAULT NULL,
  `set_warehouse` varchar(140) DEFAULT NULL,
  `tc_name` varchar(140) DEFAULT NULL,
  `terms` longtext DEFAULT NULL,
  `status` varchar(140) DEFAULT NULL,
  `per_ordered` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `transfer_status` varchar(140) DEFAULT NULL,
  `per_received` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `letter_head` varchar(140) DEFAULT NULL,
  `select_print_heading` varchar(140) DEFAULT NULL,
  `job_card` varchar(140) DEFAULT NULL,
  `work_order` varchar(140) DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `company` (`company`),
  KEY `transaction_date` (`transaction_date`),
  KEY `status` (`status`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabMaterial Request Item` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `item_code` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_uom` varchar(140) DEFAULT NULL,
  `from_warehouse` varchar(140) DEFAULT NULL,
  `warehouse` varchar(140) DEFAULT NULL,
  `uom` varchar(140) DEFAULT NULL,
  `conversion_factor` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `min_order_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `projected_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `actual_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `ordered_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `received_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `expense_account` varchar(140) DEFAULT NULL,
  `wip_composite_asset` varchar(140) DEFAULT NULL,
  `manufacturer` varchar(140) DEFAULT NULL,
  `manufacturer_part_no` varchar(140) DEFAULT NULL,
  `bom_no` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `lead_time_date` date DEFAULT NULL,
  `sales_order` varchar(140) DEFAULT NULL,
  `sales_order_item` varchar(140) DEFAULT NULL,
  `production_plan` varchar(140) DEFAULT NULL,
  `material_request_plan_item` varchar(140) DEFAULT NULL,
  `job_card_item` varchar(140) DEFAULT NULL,
  `page_break` tinyint(4) NOT NULL DEFAULT 0,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `item_code` (`item_code`),
  KEY `item_name` (`item_name`),
  KEY `item_group` (`item_group`),
  KEY `sales_order_item` (`sales_order_item`),
  KEY `parent` (`parent`),
  KEY `item_code_warehouse_index` (`item_code`,`warehouse`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabRequest for Quotation` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `naming_series` varchar(140) DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `billing_address` varchar(140) DEFAULT NULL,
  `billing_address_display` longtext DEFAULT NULL,
  `vendor` varchar(140) DEFAULT NULL,
  `transaction_date` date DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `status` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `email_template` varchar(140) DEFAULT NULL,
  `send_attached_files` tinyint(4) NOT NULL DEFAULT 1,
  `send_document_print` tinyint(4) NOT NULL DEFAULT 0,
  `message_for_supplier` longtext DEFAULT NULL,
  `incoterm` varchar(140) DEFAULT NULL,
  `named_place` varchar(140) DEFAULT NULL,
  `tc_name` varchar(140) DEFAULT NULL,
  `terms` longtext DEFAULT NULL,
  `select_print_heading` varchar(140) DEFAULT NULL,
  `letter_head` varchar(140) DEFAULT NULL,
  `opportunity` varchar(140) DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `company` (`company`),
  KEY `transaction_date` (`transaction_date`),
  KEY `status` (`status`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabRequest for Quotation Item` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `item_code` varchar(140) DEFAULT NULL,
  `supplier_part_no` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_uom` varchar(140) DEFAULT NULL,
  `uom` varchar(140) DEFAULT NULL,
  `conversion_factor` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `warehouse` varchar(140) DEFAULT NULL,
  `material_request` varchar(140) DEFAULT NULL,
  `material_request_item` varchar(140) DEFAULT NULL,
  `project_name` varchar(140) DEFAULT NULL,
  `page_break` tinyint(4) NOT NULL DEFAULT 0,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `item_code` (`item_code`),
  KEY `item_name` (`item_name`),
  KEY `parent` (`parent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabSupplier Quotation` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `title` varchar(140) DEFAULT '{supplier_name}',
  `naming_series` varchar(140) DEFAULT NULL,
  `supplier` varchar(140) DEFAULT NULL,
  `supplier_name` varchar(140) DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `status` varchar(140) DEFAULT NULL,
  `transaction_date` date DEFAULT NULL,
  `valid_till` date DEFAULT NULL,
  `quotation_number` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `currency` varchar(140) DEFAULT NULL,
  `conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `buying_price_list` varchar(140) DEFAULT NULL,
  `price_list_currency` varchar(140) DEFAULT NULL,
  `plc_conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `ignore_pricing_rule` tinyint(4) NOT NULL DEFAULT 0,
  `total_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_net_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `tax_category` varchar(140) DEFAULT NULL,
  `taxes_and_charges` varchar(140) DEFAULT NULL,
  `shipping_rule` varchar(140) DEFAULT NULL,
  `incoterm` varchar(140) DEFAULT NULL,
  `named_place` varchar(140) DEFAULT NULL,
  `base_taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `apply_discount_on` varchar(140) DEFAULT 'Grand Total',
  `base_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `additional_discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_in_words` varchar(240) DEFAULT NULL,
  `grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `in_words` varchar(240) DEFAULT NULL,
  `disable_rounded_total` tinyint(4) NOT NULL DEFAULT 0,
  `other_charges_calculation` longtext DEFAULT NULL,
  `supplier_address` varchar(140) DEFAULT NULL,
  `address_display` longtext DEFAULT NULL,
  `contact_person` varchar(140) DEFAULT NULL,
  `contact_display` text DEFAULT NULL,
  `contact_mobile` text DEFAULT NULL,
  `contact_email` varchar(140) DEFAULT NULL,
  `shipping_address` varchar(140) DEFAULT NULL,
  `shipping_address_display` longtext DEFAULT NULL,
  `billing_address` varchar(140) DEFAULT NULL,
  `billing_address_display` longtext DEFAULT NULL,
  `tc_name` varchar(140) DEFAULT NULL,
  `terms` longtext DEFAULT NULL,
  `letter_head` varchar(140) DEFAULT NULL,
  `group_same_items` tinyint(4) NOT NULL DEFAULT 0,
  `select_print_heading` varchar(140) DEFAULT NULL,
  `language` varchar(140) DEFAULT NULL,
  `auto_repeat` varchar(140) DEFAULT NULL,
  `is_subcontracted` tinyint(4) NOT NULL DEFAULT 0,
  `opportunity` varchar(140) DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `supplier` (`supplier`),
  KEY `company` (`company`),
  KEY `status` (`status`),
  KEY `transaction_date` (`transaction_date`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabSupplier Quotation Item` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `item_code` varchar(140) DEFAULT NULL,
  `supplier_part_no` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `lead_time_days` int(11) NOT NULL DEFAULT 0,
  `expected_delivery_date` date DEFAULT NULL,
  `is_free_item` tinyint(4) NOT NULL DEFAULT 0,
  `description` longtext DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_uom` varchar(140) DEFAULT NULL,
  `uom` varchar(140) DEFAULT NULL,
  `conversion_factor` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `distributed_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `item_tax_template` varchar(140) DEFAULT NULL,
  `base_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `pricing_rules` text DEFAULT NULL,
  `net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `weight_per_unit` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `weight_uom` varchar(140) DEFAULT NULL,
  `warehouse` varchar(140) DEFAULT NULL,
  `prevdoc_doctype` varchar(140) DEFAULT NULL,
  `material_request` varchar(140) DEFAULT NULL,
  `sales_order` varchar(140) DEFAULT NULL,
  `request_for_quotation` varchar(140) DEFAULT NULL,
  `material_request_item` varchar(140) DEFAULT NULL,
  `request_for_quotation_item` varchar(140) DEFAULT NULL,
  `item_tax_rate` longtext DEFAULT NULL,
  `manufacturer` varchar(140) DEFAULT NULL,
  `manufacturer_part_no` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `page_break` tinyint(4) NOT NULL DEFAULT 0,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `item_code` (`item_code`),
  KEY `item_name` (`item_name`),
  KEY `material_request` (`material_request`),
  KEY `sales_order` (`sales_order`),
  KEY `material_request_item` (`material_request_item`),
  KEY `parent` (`parent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPurchase Order` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `title` varchar(140) DEFAULT '{supplier_name}',
  `naming_series` varchar(140) DEFAULT NULL,
  `supplier` varchar(140) DEFAULT NULL,
  `supplier_name` varchar(140) DEFAULT NULL,
  `order_confirmation_no` varchar(140) DEFAULT NULL,
  `order_confirmation_date` date DEFAULT NULL,
  `transaction_date` date DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `apply_tds` tinyint(4) NOT NULL DEFAULT 0,
  `tax_withholding_category` varchar(140) DEFAULT NULL,
  `is_subcontracted` tinyint(4) NOT NULL DEFAULT 0,
  `supplier_warehouse` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `currency` varchar(140) DEFAULT NULL,
  `conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `buying_price_list` varchar(140) DEFAULT NULL,
  `price_list_currency` varchar(140) DEFAULT NULL,
  `plc_conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `ignore_pricing_rule` tinyint(4) NOT NULL DEFAULT 0,
  `scan_barcode` varchar(140) DEFAULT NULL,
  `set_from_warehouse` varchar(140) DEFAULT NULL,
  `set_warehouse` varchar(140) DEFAULT NULL,
  `total_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_net_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `tax_withholding_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_tax_withholding_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `set_reserve_warehouse` varchar(140) DEFAULT NULL,
  `tax_category` varchar(140) DEFAULT NULL,
  `taxes_and_charges` varchar(140) DEFAULT NULL,
  `shipping_rule` varchar(140) DEFAULT NULL,
  `incoterm` varchar(140) DEFAULT NULL,
  `named_place` varchar(140) DEFAULT NULL,
  `base_taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_in_words` varchar(240) DEFAULT NULL,
  `base_rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `disable_rounded_total` tinyint(4) NOT NULL DEFAULT 0,
  `in_words` varchar(240) DEFAULT NULL,
  `advance_paid` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `apply_discount_on` varchar(140) DEFAULT 'Grand Total',
  `base_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `additional_discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `other_charges_calculation` longtext DEFAULT NULL,
  `supplier_address` varchar(140) DEFAULT NULL,
  `address_display` longtext DEFAULT NULL,
  `contact_person` varchar(140) DEFAULT NULL,
  `contact_display` text DEFAULT NULL,
  `contact_mobile` text DEFAULT NULL,
  `contact_email` text DEFAULT NULL,
  `shipping_address` varchar(140) DEFAULT NULL,
  `shipping_address_display` longtext DEFAULT NULL,
  `billing_address` varchar(140) DEFAULT NULL,
  `billing_address_display` longtext DEFAULT NULL,
  `customer` varchar(140) DEFAULT NULL,
  `customer_name` varchar(140) DEFAULT NULL,
  `customer_contact_person` varchar(140) DEFAULT NULL,
  `customer_contact_display` text DEFAULT NULL,
  `customer_contact_mobile` text DEFAULT NULL,
  `customer_contact_email` longtext DEFAULT NULL,
  `payment_terms_template` varchar(140) DEFAULT NULL,
  `tc_name` varchar(140) DEFAULT NULL,
  `terms` longtext DEFAULT NULL,
  `status` varchar(140) DEFAULT 'Draft',
  `advance_payment_status` varchar(140) DEFAULT NULL,
  `per_billed` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `per_received` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `letter_head` varchar(140) DEFAULT NULL,
  `group_same_items` tinyint(4) NOT NULL DEFAULT 0,
  `select_print_heading` varchar(140) DEFAULT NULL,
  `language` varchar(140) DEFAULT NULL,
  `from_date` date DEFAULT NULL,
  `to_date` date DEFAULT NULL,
  `auto_repeat` varchar(140) DEFAULT NULL,
  `is_internal_supplier` tinyint(4) NOT NULL DEFAULT 0,
  `represents_company` varchar(140) DEFAULT NULL,
  `ref_sq` varchar(140) DEFAULT NULL,
  `party_account_currency` varchar(140) DEFAULT NULL,
  `inter_company_order_reference` varchar(140) DEFAULT NULL,
  `is_old_subcontracting_flow` tinyint(4) NOT NULL DEFAULT 0,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `supplier` (`supplier`),
  KEY `transaction_date` (`transaction_date`),
  KEY `status` (`status`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPurchase Order Item` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `fg_item` varchar(140) DEFAULT NULL,
  `fg_item_qty` decimal(21,9) NOT NULL DEFAULT 1.000000000,
  `item_code` varchar(140) DEFAULT NULL,
  `supplier_part_no` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `product_bundle` varchar(140) DEFAULT NULL,
  `schedule_date` date DEFAULT NULL,
  `expected_delivery_date` date DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `image` text DEFAULT NULL,
  `qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_uom` varchar(140) DEFAULT NULL,
  `subcontracted_quantity` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `uom` varchar(140) DEFAULT NULL,
  `conversion_factor` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `stock_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `last_purchase_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `margin_type` varchar(140) DEFAULT NULL,
  `margin_rate_or_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate_with_margin` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `distributed_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rate_with_margin` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `item_tax_template` varchar(140) DEFAULT NULL,
  `base_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `pricing_rules` text DEFAULT NULL,
  `stock_uom_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `is_free_item` tinyint(4) NOT NULL DEFAULT 0,
  `apply_tds` tinyint(4) NOT NULL DEFAULT 1,
  `net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `from_warehouse` varchar(140) DEFAULT NULL,
  `warehouse` varchar(140) DEFAULT NULL,
  `actual_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `company_total_stock` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `material_request` varchar(140) DEFAULT NULL,
  `material_request_item` varchar(140) DEFAULT NULL,
  `sales_order` varchar(140) DEFAULT NULL,
  `sales_order_item` varchar(140) DEFAULT NULL,
  `sales_order_packed_item` varchar(140) DEFAULT NULL,
  `supplier_quotation` varchar(140) DEFAULT NULL,
  `supplier_quotation_item` varchar(140) DEFAULT NULL,
  `delivered_by_supplier` tinyint(4) NOT NULL DEFAULT 0,
  `against_blanket_order` tinyint(4) NOT NULL DEFAULT 0,
  `blanket_order` varchar(140) DEFAULT NULL,
  `blanket_order_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `received_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `returned_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `billed_amt` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `expense_account` varchar(140) DEFAULT NULL,
  `wip_composite_asset` varchar(140) DEFAULT NULL,
  `manufacturer` varchar(140) DEFAULT NULL,
  `manufacturer_part_no` varchar(140) DEFAULT NULL,
  `bom` varchar(140) DEFAULT NULL,
  `include_exploded_items` tinyint(4) NOT NULL DEFAULT 0,
  `weight_per_unit` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `weight_uom` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `is_fixed_asset` tinyint(4) NOT NULL DEFAULT 0,
  `item_tax_rate` longtext DEFAULT NULL,
  `production_plan` varchar(140) DEFAULT NULL,
  `production_plan_item` varchar(140) DEFAULT NULL,
  `production_plan_sub_assembly_item` varchar(140) DEFAULT NULL,
  `page_break` tinyint(4) NOT NULL DEFAULT 0,
  `job_card` varchar(140) DEFAULT NULL,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `expected_delivery_date` (`expected_delivery_date`),
  KEY `material_request` (`material_request`),
  KEY `material_request_item` (`material_request_item`),
  KEY `sales_order` (`sales_order`),
  KEY `sales_order_item` (`sales_order_item`),
  KEY `job_card` (`job_card`),
  KEY `parent` (`parent`),
  KEY `item_code_warehouse_index` (`item_code`,`warehouse`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPurchase Invoice` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `title` varchar(140) DEFAULT '{supplier_name}',
  `naming_series` varchar(140) DEFAULT NULL,
  `supplier` varchar(140) DEFAULT NULL,
  `supplier_name` varchar(140) DEFAULT NULL,
  `tax_id` varchar(140) DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `posting_time` time(6) DEFAULT NULL,
  `set_posting_time` tinyint(4) NOT NULL DEFAULT 0,
  `due_date` date DEFAULT NULL,
  `is_paid` tinyint(4) NOT NULL DEFAULT 0,
  `is_return` tinyint(4) NOT NULL DEFAULT 0,
  `return_against` varchar(140) DEFAULT NULL,
  `update_outstanding_for_self` tinyint(4) NOT NULL DEFAULT 1,
  `update_billed_amount_in_purchase_order` tinyint(4) NOT NULL DEFAULT 0,
  `update_billed_amount_in_purchase_receipt` tinyint(4) NOT NULL DEFAULT 1,
  `apply_tds` tinyint(4) NOT NULL DEFAULT 0,
  `tax_withholding_category` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `bill_no` varchar(140) DEFAULT NULL,
  `bill_date` date DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `currency` varchar(140) DEFAULT NULL,
  `conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `use_transaction_date_exchange_rate` tinyint(4) NOT NULL DEFAULT 0,
  `buying_price_list` varchar(140) DEFAULT NULL,
  `price_list_currency` varchar(140) DEFAULT NULL,
  `plc_conversion_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `ignore_pricing_rule` tinyint(4) NOT NULL DEFAULT 0,
  `scan_barcode` varchar(140) DEFAULT NULL,
  `update_stock` tinyint(4) NOT NULL DEFAULT 0,
  `set_warehouse` varchar(140) DEFAULT NULL,
  `set_from_warehouse` varchar(140) DEFAULT NULL,
  `is_subcontracted` tinyint(4) NOT NULL DEFAULT 0,
  `rejected_warehouse` varchar(140) DEFAULT NULL,
  `supplier_warehouse` varchar(140) DEFAULT NULL,
  `total_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_net_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `tax_withholding_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_tax_withholding_net_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `tax_category` varchar(140) DEFAULT NULL,
  `taxes_and_charges` varchar(140) DEFAULT NULL,
  `shipping_rule` varchar(140) DEFAULT NULL,
  `incoterm` varchar(140) DEFAULT NULL,
  `named_place` varchar(140) DEFAULT NULL,
  `base_taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_added` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `taxes_and_charges_deducted` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_in_words` varchar(240) DEFAULT NULL,
  `grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rounding_adjustment` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `use_company_roundoff_cost_center` tinyint(4) NOT NULL DEFAULT 0,
  `rounded_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `in_words` varchar(240) DEFAULT NULL,
  `total_advance` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `outstanding_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `disable_rounded_total` tinyint(4) NOT NULL DEFAULT 0,
  `apply_discount_on` varchar(140) DEFAULT 'Grand Total',
  `base_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `additional_discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `other_charges_calculation` longtext DEFAULT NULL,
  `mode_of_payment` varchar(140) DEFAULT NULL,
  `base_paid_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `clearance_date` date DEFAULT NULL,
  `cash_bank_account` varchar(140) DEFAULT NULL,
  `paid_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `allocate_advances_automatically` tinyint(4) NOT NULL DEFAULT 0,
  `only_include_allocated_payments` tinyint(4) NOT NULL DEFAULT 0,
  `write_off_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_write_off_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `write_off_account` varchar(140) DEFAULT NULL,
  `write_off_cost_center` varchar(140) DEFAULT NULL,
  `supplier_address` varchar(140) DEFAULT NULL,
  `address_display` longtext DEFAULT NULL,
  `contact_person` varchar(140) DEFAULT NULL,
  `contact_display` text DEFAULT NULL,
  `contact_mobile` text DEFAULT NULL,
  `contact_email` text DEFAULT NULL,
  `shipping_address` varchar(140) DEFAULT NULL,
  `shipping_address_display` longtext DEFAULT NULL,
  `billing_address` varchar(140) DEFAULT NULL,
  `billing_address_display` longtext DEFAULT NULL,
  `payment_terms_template` varchar(140) DEFAULT NULL,
  `ignore_default_payment_terms_template` tinyint(4) NOT NULL DEFAULT 0,
  `tc_name` varchar(140) DEFAULT NULL,
  `terms` longtext DEFAULT NULL,
  `status` varchar(140) DEFAULT 'Draft',
  `per_received` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `credit_to` varchar(140) DEFAULT NULL,
  `party_account_currency` varchar(140) DEFAULT NULL,
  `is_opening` varchar(140) DEFAULT 'No',
  `against_expense_account` text DEFAULT NULL,
  `unrealized_profit_loss_account` varchar(140) DEFAULT NULL,
  `subscription` varchar(140) DEFAULT NULL,
  `auto_repeat` varchar(140) DEFAULT NULL,
  `from_date` date DEFAULT NULL,
  `to_date` date DEFAULT NULL,
  `letter_head` varchar(140) DEFAULT NULL,
  `group_same_items` tinyint(4) NOT NULL DEFAULT 0,
  `select_print_heading` varchar(140) DEFAULT NULL,
  `language` varchar(140) DEFAULT NULL,
  `on_hold` tinyint(4) NOT NULL DEFAULT 0,
  `release_date` date DEFAULT NULL,
  `hold_comment` text DEFAULT NULL,
  `is_internal_supplier` tinyint(4) NOT NULL DEFAULT 0,
  `represents_company` varchar(140) DEFAULT NULL,
  `supplier_group` varchar(140) DEFAULT NULL,
  `sender` varchar(140) DEFAULT NULL,
  `inter_company_invoice_reference` varchar(140) DEFAULT NULL,
  `is_old_subcontracting_flow` tinyint(4) NOT NULL DEFAULT 0,
  `remarks` text DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `supplier` (`supplier`),
  KEY `posting_date` (`posting_date`),
  KEY `return_against` (`return_against`),
  KEY `bill_no` (`bill_no`),
  KEY `credit_to` (`credit_to`),
  KEY `release_date` (`release_date`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPurchase Invoice Item` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `item_code` varchar(140) DEFAULT NULL,
  `product_bundle` varchar(140) DEFAULT NULL,
  `item_name` varchar(140) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `brand` varchar(140) DEFAULT NULL,
  `item_group` varchar(140) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `received_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rejected_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `uom` varchar(140) DEFAULT NULL,
  `conversion_factor` decimal(21,9) NOT NULL DEFAULT 1.000000000,
  `stock_uom` varchar(140) DEFAULT NULL,
  `stock_qty` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_price_list_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `margin_type` varchar(140) DEFAULT NULL,
  `margin_rate_or_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate_with_margin` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_percentage` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `distributed_discount_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_rate_with_margin` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `item_tax_template` varchar(140) DEFAULT NULL,
  `base_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `pricing_rules` text DEFAULT NULL,
  `stock_uom_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `is_free_item` tinyint(4) NOT NULL DEFAULT 0,
  `apply_tds` tinyint(4) NOT NULL DEFAULT 1,
  `net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_net_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `valuation_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `sales_incoming_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `item_tax_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `landed_cost_voucher_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `rm_supp_cost` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `warehouse` varchar(140) DEFAULT NULL,
  `serial_and_batch_bundle` varchar(140) DEFAULT NULL,
  `use_serial_batch_fields` tinyint(4) NOT NULL DEFAULT 0,
  `from_warehouse` varchar(140) DEFAULT NULL,
  `quality_inspection` varchar(140) DEFAULT NULL,
  `rejected_warehouse` varchar(140) DEFAULT NULL,
  `rejected_serial_and_batch_bundle` varchar(140) DEFAULT NULL,
  `serial_no` text DEFAULT NULL,
  `rejected_serial_no` text DEFAULT NULL,
  `batch_no` varchar(140) DEFAULT NULL,
  `manufacturer` varchar(140) DEFAULT NULL,
  `manufacturer_part_no` varchar(140) DEFAULT NULL,
  `expense_account` varchar(140) DEFAULT NULL,
  `wip_composite_asset` varchar(140) DEFAULT NULL,
  `is_fixed_asset` tinyint(4) NOT NULL DEFAULT 0,
  `asset_location` varchar(140) DEFAULT NULL,
  `asset_category` varchar(140) DEFAULT NULL,
  `deferred_expense_account` varchar(140) DEFAULT NULL,
  `service_stop_date` date DEFAULT NULL,
  `enable_deferred_expense` tinyint(4) NOT NULL DEFAULT 0,
  `service_start_date` date DEFAULT NULL,
  `service_end_date` date DEFAULT NULL,
  `allow_zero_valuation_rate` tinyint(4) NOT NULL DEFAULT 0,
  `item_tax_rate` longtext DEFAULT NULL,
  `bom` varchar(140) DEFAULT NULL,
  `include_exploded_items` tinyint(4) NOT NULL DEFAULT 0,
  `purchase_invoice_item` varchar(140) DEFAULT NULL,
  `purchase_order` varchar(140) DEFAULT NULL,
  `po_detail` varchar(140) DEFAULT NULL,
  `purchase_receipt` varchar(140) DEFAULT NULL,
  `pr_detail` varchar(140) DEFAULT NULL,
  `sales_invoice_item` varchar(140) DEFAULT NULL,
  `material_request` varchar(140) DEFAULT NULL,
  `material_request_item` varchar(140) DEFAULT NULL,
  `weight_per_unit` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_weight` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `weight_uom` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `page_break` tinyint(4) NOT NULL DEFAULT 0,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `item_code` (`item_code`),
  KEY `serial_and_batch_bundle` (`serial_and_batch_bundle`),
  KEY `batch_no` (`batch_no`),
  KEY `purchase_order` (`purchase_order`),
  KEY `po_detail` (`po_detail`),
  KEY `purchase_receipt` (`purchase_receipt`),
  KEY `pr_detail` (`pr_detail`),
  KEY `material_request` (`material_request`),
  KEY `material_request_item` (`material_request_item`),
  KEY `project` (`project`),
  KEY `parent` (`parent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPayment Request` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `payment_request_type` varchar(140) DEFAULT 'Inward',
  `transaction_date` date DEFAULT NULL,
  `failed_reason` varchar(140) DEFAULT NULL,
  `naming_series` varchar(140) DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `mode_of_payment` varchar(140) DEFAULT NULL,
  `party_type` varchar(140) DEFAULT NULL,
  `party` varchar(140) DEFAULT NULL,
  `party_name` varchar(140) DEFAULT NULL,
  `reference_doctype` varchar(140) DEFAULT NULL,
  `reference_name` varchar(140) DEFAULT NULL,
  `grand_total` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `currency` varchar(140) DEFAULT NULL,
  `is_a_subscription` tinyint(4) NOT NULL DEFAULT 0,
  `outstanding_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `party_account_currency` varchar(140) DEFAULT NULL,
  `bank_account` varchar(140) DEFAULT NULL,
  `bank` varchar(140) DEFAULT NULL,
  `bank_account_no` varchar(140) DEFAULT NULL,
  `account` varchar(140) DEFAULT NULL,
  `iban` varchar(140) DEFAULT NULL,
  `branch_code` varchar(140) DEFAULT NULL,
  `swift_number` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `print_format` varchar(140) DEFAULT NULL,
  `email_to` varchar(140) DEFAULT NULL,
  `subject` varchar(140) DEFAULT NULL,
  `payment_gateway_account` varchar(140) DEFAULT NULL,
  `status` varchar(140) DEFAULT 'Draft',
  `make_sales_invoice` tinyint(4) NOT NULL DEFAULT 0,
  `message` text DEFAULT NULL,
  `mute_email` tinyint(4) NOT NULL DEFAULT 0,
  `payment_gateway` varchar(140) DEFAULT NULL,
  `payment_account` varchar(140) DEFAULT NULL,
  `payment_channel` varchar(140) DEFAULT NULL,
  `payment_order` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `payment_url` varchar(500) DEFAULT NULL,
  `phone_number` varchar(140) DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `reference_name` (`reference_name`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPayment Entry` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `naming_series` varchar(140) DEFAULT NULL,
  `payment_type` varchar(140) DEFAULT NULL,
  `payment_order_status` varchar(140) DEFAULT NULL,
  `posting_date` date DEFAULT NULL,
  `company` varchar(140) DEFAULT NULL,
  `mode_of_payment` varchar(140) DEFAULT NULL,
  `party_type` varchar(140) DEFAULT NULL,
  `party` varchar(140) DEFAULT NULL,
  `party_name` varchar(140) DEFAULT NULL,
  `book_advance_payments_in_separate_party_account` tinyint(4) NOT NULL DEFAULT 0,
  `reconcile_on_advance_payment_date` tinyint(4) NOT NULL DEFAULT 0,
  `advance_reconciliation_takes_effect_on` varchar(140) DEFAULT 'Oldest Of Invoice Or Advance',
  `bank_account` varchar(140) DEFAULT NULL,
  `party_bank_account` varchar(140) DEFAULT NULL,
  `contact_person` varchar(140) DEFAULT NULL,
  `contact_email` varchar(140) DEFAULT NULL,
  `paid_from` varchar(140) DEFAULT NULL,
  `paid_from_account_type` varchar(140) DEFAULT NULL,
  `paid_from_account_currency` varchar(140) DEFAULT NULL,
  `paid_to` varchar(140) DEFAULT NULL,
  `paid_to_account_type` varchar(140) DEFAULT NULL,
  `paid_to_account_currency` varchar(140) DEFAULT NULL,
  `paid_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `paid_amount_after_tax` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `source_exchange_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_paid_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_paid_amount_after_tax` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `received_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `received_amount_after_tax` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `target_exchange_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_received_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_received_amount_after_tax` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_allocated_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `base_total_allocated_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `unallocated_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `difference_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `purchase_taxes_and_charges_template` varchar(140) DEFAULT NULL,
  `sales_taxes_and_charges_template` varchar(140) DEFAULT NULL,
  `apply_tax_withholding_amount` tinyint(4) NOT NULL DEFAULT 0,
  `tax_withholding_category` varchar(140) DEFAULT NULL,
  `base_total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `total_taxes_and_charges` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `reference_no` varchar(140) DEFAULT NULL,
  `reference_date` date DEFAULT NULL,
  `clearance_date` date DEFAULT NULL,
  `project` varchar(140) DEFAULT NULL,
  `cost_center` varchar(140) DEFAULT NULL,
  `status` varchar(140) DEFAULT 'Draft',
  `custom_remarks` tinyint(4) NOT NULL DEFAULT 0,
  `remarks` text DEFAULT NULL,
  `base_in_words` text DEFAULT NULL,
  `is_opening` varchar(140) DEFAULT 'No',
  `letter_head` varchar(140) DEFAULT NULL,
  `print_heading` varchar(140) DEFAULT NULL,
  `bank` varchar(140) DEFAULT NULL,
  `bank_account_no` varchar(140) DEFAULT NULL,
  `payment_order` varchar(140) DEFAULT NULL,
  `in_words` text DEFAULT NULL,
  `auto_repeat` varchar(140) DEFAULT NULL,
  `amended_from` varchar(140) DEFAULT NULL,
  `title` varchar(140) DEFAULT NULL,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `party_type` (`party_type`),
  KEY `reference_date` (`reference_date`),
  KEY `is_opening` (`is_opening`),
  KEY `creation` (`creation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabPayment Entry Reference` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `reference_doctype` varchar(140) DEFAULT NULL,
  `reference_name` varchar(140) DEFAULT NULL,
  `due_date` date DEFAULT NULL,
  `bill_no` varchar(140) DEFAULT NULL,
  `payment_term` varchar(140) DEFAULT NULL,
  `payment_term_outstanding` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `account_type` varchar(140) DEFAULT NULL,
  `payment_type` varchar(140) DEFAULT NULL,
  `reconcile_effect_on` date DEFAULT NULL,
  `total_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `outstanding_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `allocated_amount` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `exchange_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `exchange_gain_loss` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `account` varchar(140) DEFAULT NULL,
  `payment_request` varchar(140) DEFAULT NULL,
  `parent` varchar(140) DEFAULT NULL,
  `parentfield` varchar(140) DEFAULT NULL,
  `parenttype` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `reference_doctype` (`reference_doctype`),
  KEY `reference_name` (`reference_name`),
  KEY `parent` (`parent`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

CREATE TABLE `tabAccount` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` tinyint(4) NOT NULL DEFAULT 0,
  `idx` int(11) NOT NULL DEFAULT 0,
  `disabled` tinyint(4) NOT NULL DEFAULT 0,
  `account_name` varchar(140) DEFAULT NULL,
  `account_number` varchar(140) DEFAULT NULL,
  `is_group` tinyint(4) NOT NULL DEFAULT 0,
  `company` varchar(140) DEFAULT NULL,
  `root_type` varchar(140) DEFAULT NULL,
  `report_type` varchar(140) DEFAULT NULL,
  `account_currency` varchar(140) DEFAULT NULL,
  `parent_account` varchar(140) DEFAULT NULL,
  `account_type` varchar(140) DEFAULT NULL,
  `tax_rate` decimal(21,9) NOT NULL DEFAULT 0.000000000,
  `freeze_account` varchar(140) DEFAULT NULL,
  `balance_must_be` varchar(140) DEFAULT NULL,
  `lft` int(11) NOT NULL DEFAULT 0,
  `rgt` int(11) NOT NULL DEFAULT 0,
  `old_parent` varchar(140) DEFAULT NULL,
  `include_in_gross` tinyint(4) NOT NULL DEFAULT 0,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `parent_account` (`parent_account`),
  KEY `account_type` (`account_type`),
  KEY `lft` (`lft`),
  KEY `rgt` (`rgt`),
  KEY `creation` (`creation`),
  KEY `lft_rgt_index` (`lft`,`rgt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
